"use client";

import { useState } from "react";
import jsPDF from "jspdf";
import Map from "../components/Map";
import SearchPill from "../components/SearchPill";
import TelemetryCards from "../components/TelemetryCards";
import ActionBar from "../components/ActionBar";

export default function Home() {
  const [theme, setTheme] = useState<"dark" | "light">("dark");
  const [telemetry, setTelemetry] = useState<any>(null);
  const [location, setLocation] = useState({ lat: 25.7617, lng: -80.1918 });
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const toggleTheme = () => {
    setTheme((prev) => (prev === "dark" ? "light" : "dark"));
  };

  const exportPDF = () => {
    if (!telemetry || isLoading) {
      alert("Please generate a valid risk report first.");
      return;
    }

    const doc = new jsPDF();
    doc.setFont("helvetica", "bold");
    doc.setFontSize(24);
    doc.setTextColor(20, 20, 20);
    doc.text("Earth-Y Risk Intelligence", 20, 30);
    doc.setFontSize(12);
    doc.setFont("helvetica", "normal");
    doc.setTextColor(100, 100, 100);
    doc.text("Automated Coastal Morphology Projection", 20, 40);
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 45, 190, 45);
    doc.setFontSize(16);
    doc.setFont("helvetica", "bold");
    doc.setTextColor(20, 20, 20);
    doc.text(`Target Asset: ${telemetry.city.toUpperCase()} COASTLINE`, 20, 65);
    doc.setFontSize(14);
    doc.setFont("helvetica", "normal");
    doc.text(`Projected Horizontal Land Loss: ${telemetry.landLoss}`, 20, 85);
    
    if (telemetry.risk === "Critical") doc.setTextColor(230, 0, 0);
    else if (telemetry.risk === "Elevated") doc.setTextColor(200, 100, 0);
    
    doc.text(`Infrastructural Risk Level: ${telemetry.risk}`, 20, 95);
    doc.setTextColor(20, 20, 20);
    doc.text(`Physics-Informed Confidence: ${telemetry.confidence}`, 20, 105);
    doc.text(`Projection Horizon: Year ${telemetry.year}`, 20, 115);
    doc.setFontSize(10);
    doc.setTextColor(150, 150, 150);
    doc.text("Generated by the Earth-Y AI Engine. Powered by Google Earth Engine & PyTorch.", 20, 280);
    doc.save(`Earth_Y_Report_${telemetry.city.replace(/\s+/g, '_')}.pdf`);
  };

  const handleSearch = async (city: string) => {
    setIsLoading(true);
    setError(null);
    setTelemetry(null);

    try {
      const mapboxToken = process.env.NEXT_PUBLIC_MAPBOX_TOKEN;
      const geoRes = await fetch(`https://api.mapbox.com/geocoding/v5/mapbox.places/${encodeURIComponent(city)}.json?access_token=${mapboxToken}`);
      const geoData = await geoRes.json();

      if (!geoData.features || geoData.features.length === 0) {
        setError("Location not found. Please verify the city name.");
        setIsLoading(false);
        return;
      }

      const [lng, lat] = geoData.features[0].center;
      setLocation({ lat, lng });

      const response = await fetch("http://localhost:8000/api/predict", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ city: city, lat: lat, lng: lng }),
      });
      
      if (!response.ok) throw new Error("Backend connection failed.");

      const data = await response.json();
      setTelemetry(data);
    } catch (err) {
      console.error(err);
      setError("Engine offline. Could not connect to PyTorch backend.");
    } finally {
      setIsLoading(false);
    }
  };

  return (
    <main data-theme={theme}>
      <Map theme={theme} lat={location.lat} lng={location.lng} />
      
      {error && (
        <div style={{ position: "absolute", top: "6rem", left: "50%", transform: "translateX(-50%)", background: "rgba(230, 0, 0, 0.9)", color: "white", padding: "0.75rem 1.5rem", borderRadius: "8px", zIndex: 20, backdropFilter: "blur(10px)", fontWeight: 500, boxShadow: "0 4px 12px rgba(0,0,0,0.2)" }}>
          {error}
        </div>
      )}

      <SearchPill onSearch={handleSearch} isLoading={isLoading} />
      <TelemetryCards data={telemetry} />
      <ActionBar onToggleTheme={toggleTheme} onExportPDF={exportPDF} />
    </main>
  );
}